# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 50, 861, 501))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBeds = QtWidgets.QWidget()
        self.tabBeds.setObjectName("tabBeds")
        self.scrollArea = QtWidgets.QScrollArea(self.tabBeds)
        self.scrollArea.setGeometry(QtCore.QRect(0, 60, 851, 411))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 849, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 851, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BedGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.BedGroupBox.setMinimumSize(QtCore.QSize(849, 120))
        self.BedGroupBox.setObjectName("BedGroupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.BedGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 20, 741, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ModulemonitorsGroupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.ModulemonitorsGroupBox.setObjectName("ModulemonitorsGroupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.ModulemonitorsGroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 761, 361))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MonitorGroupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.MonitorGroupBox.setObjectName("MonitorGroupBox")
        self.MonitorValueScale = QtWidgets.QProgressBar(self.MonitorGroupBox)
        self.MonitorValueScale.setGeometry(QtCore.QRect(0, 20, 118, 23))
        self.MonitorValueScale.setProperty("value", 24)
        self.MonitorValueScale.setObjectName("MonitorValueScale")
        self.MonitorCurrentValue = QtWidgets.QLCDNumber(self.MonitorGroupBox)
        self.MonitorCurrentValue.setGeometry(QtCore.QRect(130, 20, 64, 23))
        self.MonitorCurrentValue.setProperty("value", 30000.0)
        self.MonitorCurrentValue.setObjectName("MonitorCurrentValue")
        self.MonitorUnits = QtWidgets.QTextBrowser(self.MonitorGroupBox)
        self.MonitorUnits.setGeometry(QtCore.QRect(200, 20, 91, 23))
        self.MonitorUnits.setObjectName("MonitorUnits")
        self.MonitorAlarm = QtWidgets.QRadioButton(self.MonitorGroupBox)
        self.MonitorAlarm.setGeometry(QtCore.QRect(300, 20, 100, 20))
        self.MonitorAlarm.setObjectName("MonitorAlarm")
        self.MonitorCritAlarm = QtWidgets.QRadioButton(self.MonitorGroupBox)
        self.MonitorCritAlarm.setGeometry(QtCore.QRect(400, 20, 100, 20))
        self.MonitorCritAlarm.setObjectName("MonitorCritAlarm")
        self.verticalLayout_3.addWidget(self.MonitorGroupBox)
        self.verticalLayout_2.addWidget(self.ModulemonitorsGroupBox)
        self.BedAlarm = QtWidgets.QRadioButton(self.BedGroupBox)
        self.BedAlarm.setGeometry(QtCore.QRect(0, 20, 101, 20))
        self.BedAlarm.setObjectName("BedAlarm")
        self.BedCritAlarm = QtWidgets.QRadioButton(self.BedGroupBox)
        self.BedCritAlarm.setGeometry(QtCore.QRect(0, 40, 101, 20))
        self.BedCritAlarm.setObjectName("BedCritAlarm")
        self.BedAddModule = QtWidgets.QPushButton(self.BedGroupBox)
        self.BedAddModule.setGeometry(QtCore.QRect(0, 60, 101, 32))
        self.BedAddModule.setObjectName("BedAddModule")
        self.verticalLayout.addWidget(self.BedGroupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.tabBeds)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.tabBeds)
        self.comboBox.setGeometry(QtCore.QRect(150, 10, 91, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line = QtWidgets.QFrame(self.tabBeds)
        self.line.setGeometry(QtCore.QRect(0, 50, 851, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tabBeds, "")
        self.tabShifts = QtWidgets.QWidget()
        self.tabShifts.setObjectName("tabShifts")
        self.tblShifts = QtWidgets.QTableWidget(self.tabShifts)
        self.tblShifts.setGeometry(QtCore.QRect(50, 70, 581, 331))
        self.tblShifts.setLineWidth(1)
        self.tblShifts.setAlternatingRowColors(True)
        self.tblShifts.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblShifts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblShifts.setRowCount(0)
        self.tblShifts.setColumnCount(5)
        self.tblShifts.setObjectName("tblShifts")
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tabShifts, "")
        self.tabIncidents = QtWidgets.QWidget()
        self.tabIncidents.setObjectName("tabIncidents")
        self.tblIncidents = QtWidgets.QTableWidget(self.tabIncidents)
        self.tblIncidents.setGeometry(QtCore.QRect(50, 70, 581, 331))
        self.tblIncidents.setLineWidth(1)
        self.tblIncidents.setAlternatingRowColors(True)
        self.tblIncidents.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblIncidents.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblIncidents.setRowCount(0)
        self.tblIncidents.setColumnCount(4)
        self.tblIncidents.setObjectName("tblIncidents")
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tabIncidents, "")
        self.tabStaff = QtWidgets.QWidget()
        self.tabStaff.setObjectName("tabStaff")
        self.tblStaff = QtWidgets.QTableWidget(self.tabStaff)
        self.tblStaff.setGeometry(QtCore.QRect(50, 70, 711, 331))
        self.tblStaff.setLineWidth(1)
        self.tblStaff.setAlternatingRowColors(True)
        self.tblStaff.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblStaff.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblStaff.setRowCount(0)
        self.tblStaff.setColumnCount(5)
        self.tblStaff.setObjectName("tblStaff")
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(4, item)
        self.pushButton_3 = QtWidgets.QPushButton(self.tabStaff)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 10, 121, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tabStaff)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 10, 131, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tabStaff, "")
        self.tabMonitor = QtWidgets.QWidget()
        self.tabMonitor.setObjectName("tabMonitor")
        self.tblMonitorTypes = QtWidgets.QTableWidget(self.tabMonitor)
        self.tblMonitorTypes.setGeometry(QtCore.QRect(50, 70, 711, 331))
        self.tblMonitorTypes.setLineWidth(1)
        self.tblMonitorTypes.setAlternatingRowColors(True)
        self.tblMonitorTypes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblMonitorTypes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblMonitorTypes.setRowCount(0)
        self.tblMonitorTypes.setColumnCount(7)
        self.tblMonitorTypes.setObjectName("tblMonitorTypes")
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tabMonitor, "")
        self.tabModules = QtWidgets.QWidget()
        self.tabModules.setObjectName("tabModules")
        self.tblModules = QtWidgets.QTableWidget(self.tabModules)
        self.tblModules.setGeometry(QtCore.QRect(50, 70, 581, 331))
        self.tblModules.setLineWidth(1)
        self.tblModules.setAlternatingRowColors(True)
        self.tblModules.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblModules.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblModules.setRowCount(0)
        self.tblModules.setColumnCount(3)
        self.tblModules.setObjectName("tblModules")
        item = QtWidgets.QTableWidgetItem()
        self.tblModules.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModules.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModules.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.tabModules, "")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BedGroupBox.setTitle(_translate("MainWindow", "Bed ID"))
        self.ModulemonitorsGroupBox.setTitle(_translate("MainWindow", "ModuleID/Name"))
        self.MonitorGroupBox.setTitle(_translate("MainWindow", "MonitorID/Name"))
        self.MonitorUnits.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Monitor Units</p></body></html>"))
        self.MonitorAlarm.setText(_translate("MainWindow", "Alarm"))
        self.MonitorCritAlarm.setText(_translate("MainWindow", "CritAlarm"))
        self.BedAlarm.setText(_translate("MainWindow", "Alarm"))
        self.BedCritAlarm.setText(_translate("MainWindow", "CritAlarm"))
        self.BedAddModule.setText(_translate("MainWindow", "Add Module"))
        self.pushButton.setText(_translate("MainWindow", "Add Bed"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Bay 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bay 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBeds), _translate("MainWindow", "Beds"))
        item = self.tblShifts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tblShifts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Staff member"))
        item = self.tblShifts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tblShifts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        item = self.tblShifts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Hours"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabShifts), _translate("MainWindow", "Shifts"))
        item = self.tblIncidents.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date/time"))
        item = self.tblIncidents.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Monitor"))
        item = self.tblIncidents.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alert"))
        item = self.tblIncidents.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIncidents), _translate("MainWindow", "Incidents"))
        item = self.tblStaff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tblStaff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Staff member"))
        item = self.tblStaff.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tblStaff.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Number"))
        item = self.tblStaff.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Type"))
        self.pushButton_3.setText(_translate("MainWindow", "Register/sign-in"))
        self.pushButton_4.setText(_translate("MainWindow", "Manager console"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStaff), _translate("MainWindow", "Staff"))
        item = self.tblMonitorTypes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tblMonitorTypes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Monitor"))
        item = self.tblMonitorTypes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Unit"))
        item = self.tblMonitorTypes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Deflt Max"))
        item = self.tblMonitorTypes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Deflt Min"))
        item = self.tblMonitorTypes.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Danger Max"))
        item = self.tblMonitorTypes.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Danger Min"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMonitor), _translate("MainWindow", "Monitors"))
        item = self.tblModules.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Module Number"))
        item = self.tblModules.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tblModules.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Monitors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModules), _translate("MainWindow", "Modules"))
        self.label_6.setText(_translate("MainWindow", "MOD005622 Hospital Monitoring System"))
