# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/files/testwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 50, 861, 501))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBeds = QtWidgets.QWidget()
        self.tabBeds.setObjectName("tabBeds")
        self.scrollArea = QtWidgets.QScrollArea(self.tabBeds)
        self.scrollArea.setGeometry(QtCore.QRect(0, 60, 851, 431))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 849, 1572))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 223))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 223))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 223))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 223))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 223))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 223))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 223))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout.addWidget(self.groupBox_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.tabBeds)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.tabBeds)
        self.comboBox.setGeometry(QtCore.QRect(150, 10, 91, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line = QtWidgets.QFrame(self.tabBeds)
        self.line.setGeometry(QtCore.QRect(0, 50, 851, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tabBeds, "")
        self.tabShifts = QtWidgets.QWidget()
        self.tabShifts.setObjectName("tabShifts")
        self.tblShifts = QtWidgets.QTableWidget(self.tabShifts)
        self.tblShifts.setGeometry(QtCore.QRect(50, 70, 581, 331))
        self.tblShifts.setLineWidth(1)
        self.tblShifts.setAlternatingRowColors(True)
        self.tblShifts.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblShifts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblShifts.setRowCount(0)
        self.tblShifts.setColumnCount(5)
        self.tblShifts.setObjectName("tblShifts")
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShifts.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tabShifts, "")
        self.tabIncidents = QtWidgets.QWidget()
        self.tabIncidents.setObjectName("tabIncidents")
        self.tblIncidents = QtWidgets.QTableWidget(self.tabIncidents)
        self.tblIncidents.setGeometry(QtCore.QRect(50, 70, 581, 331))
        self.tblIncidents.setLineWidth(1)
        self.tblIncidents.setAlternatingRowColors(True)
        self.tblIncidents.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblIncidents.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblIncidents.setRowCount(0)
        self.tblIncidents.setColumnCount(4)
        self.tblIncidents.setObjectName("tblIncidents")
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblIncidents.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tabIncidents, "")
        self.tabStaff = QtWidgets.QWidget()
        self.tabStaff.setObjectName("tabStaff")
        self.tblStaff = QtWidgets.QTableWidget(self.tabStaff)
        self.tblStaff.setGeometry(QtCore.QRect(50, 70, 711, 331))
        self.tblStaff.setLineWidth(1)
        self.tblStaff.setAlternatingRowColors(True)
        self.tblStaff.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblStaff.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblStaff.setRowCount(0)
        self.tblStaff.setColumnCount(5)
        self.tblStaff.setObjectName("tblStaff")
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStaff.setHorizontalHeaderItem(4, item)
        self.pushButton_3 = QtWidgets.QPushButton(self.tabStaff)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 10, 121, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tabStaff)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 10, 131, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tabStaff, "")
        self.tabMonitor = QtWidgets.QWidget()
        self.tabMonitor.setObjectName("tabMonitor")
        self.tblMonitorTypes = QtWidgets.QTableWidget(self.tabMonitor)
        self.tblMonitorTypes.setGeometry(QtCore.QRect(50, 70, 711, 331))
        self.tblMonitorTypes.setLineWidth(1)
        self.tblMonitorTypes.setAlternatingRowColors(True)
        self.tblMonitorTypes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblMonitorTypes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblMonitorTypes.setRowCount(0)
        self.tblMonitorTypes.setColumnCount(7)
        self.tblMonitorTypes.setObjectName("tblMonitorTypes")
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorTypes.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tabMonitor, "")
        self.tabModules = QtWidgets.QWidget()
        self.tabModules.setObjectName("tabModules")
        self.tblModules = QtWidgets.QTableWidget(self.tabModules)
        self.tblModules.setGeometry(QtCore.QRect(50, 70, 581, 331))
        self.tblModules.setLineWidth(1)
        self.tblModules.setAlternatingRowColors(True)
        self.tblModules.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblModules.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblModules.setRowCount(0)
        self.tblModules.setColumnCount(3)
        self.tblModules.setObjectName("tblModules")
        item = QtWidgets.QTableWidgetItem()
        self.tblModules.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModules.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModules.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.tabModules, "")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton.setText(_translate("MainWindow", "Add Bed"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Bay 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bay 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBeds), _translate("MainWindow", "Beds"))
        item = self.tblShifts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tblShifts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Staff member"))
        item = self.tblShifts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tblShifts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        item = self.tblShifts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Hours"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabShifts), _translate("MainWindow", "Shifts"))
        item = self.tblIncidents.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date/time"))
        item = self.tblIncidents.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Monitor"))
        item = self.tblIncidents.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alert"))
        item = self.tblIncidents.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIncidents), _translate("MainWindow", "Incidents"))
        item = self.tblStaff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tblStaff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Staff member"))
        item = self.tblStaff.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tblStaff.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Number"))
        item = self.tblStaff.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Type"))
        self.pushButton_3.setText(_translate("MainWindow", "Register/sign-in"))
        self.pushButton_4.setText(_translate("MainWindow", "Manager console"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStaff), _translate("MainWindow", "Staff"))
        item = self.tblMonitorTypes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tblMonitorTypes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Monitor"))
        item = self.tblMonitorTypes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Unit"))
        item = self.tblMonitorTypes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Deflt Max"))
        item = self.tblMonitorTypes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Deflt Min"))
        item = self.tblMonitorTypes.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Danger Max"))
        item = self.tblMonitorTypes.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Danger Min"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMonitor), _translate("MainWindow", "Monitors"))
        item = self.tblModules.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Module Number"))
        item = self.tblModules.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tblModules.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Monitors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModules), _translate("MainWindow", "Modules"))
        self.label_6.setText(_translate("MainWindow", "MOD005622 Hospital Monitoring System"))
